#!/bin/bash
set -e
. /etc/aa/entrypointbase

Timezone=${Timezone:-""}
Host=${Host:-""}
LogTag=${LogTag:-""}

# ENTRYPOINT_LOG
#   $file         create log file
#   console(default)      echo
aaLog() {
    AaLog --aalogheader_host "${Host}" --aalogtag "${LogTag}" "$@"
}

AaAdjustTime "${Timezone}"

RunningSignal ${RunningID:-''}

if [ $# -gt 0 ]; then
	echo "Running $@"
	if [ "${1: -12}" == 'redis-server' ]; then
		su - Aa << EOF
			$@
EOF
	else
		exec "$@"
	fi
fi